[default_session]
startup_command = "nvim"

[[session]]
name = "Home ğŸ’»"
path = "~"
startup_command = "clear"

[[session]]
name = "Immozia ğŸ¡"
path = "~/Documents/work/oxianet.nosync/immozia/"
startup_command = "bash $DOTFILES/sesh/scripts/immozia"

[[session]]
name = "SRVWEBSTR01 ğŸŒ"
path = "~/Documents/servers/srvwebstr01/"
startup_command = "ssh srvwebstr01 -t 'clear && exec $SHELL'"

[[session]]
name = "PI ğŸŒ"
path = "~/Documents/servers/pi/"
startup_command = "ssh pi -t 'clear && exec $SHELL'"

[[session]]
name = "Nvim âš™ï¸"
path = "~/.config/nvim/lua"

import = ["~/.config/sesh/sesh-autogen.toml"]
