[default_session]
startup_command = "nvim"

[[session]]
name = "Home ğŸ’»"
path = "~"
startup_command = "clear"

[[session]]
name = "Immozia ğŸ¡"
path = "~/Documents/work/oxianet.nosync/immozia/"
startup_command = "bash $DOTFILES/sesh/scripts/immozia"

[[session]]
name = "SRVWEBSTR01 ğŸŒ"
path = "~/Documents/servers/srvwebstr01/"
startup_command = "ssh srvwebstr01 && clear"

[[session]]
name = "PI ğŸŒ"
path = "~/Documents/servers/pi/"
startup_command = "ssh pi && clear"
